import type { CazariLabels } from "@/components/admin/cazari/types";

type CazariLabelSources = {
  tPages: (key: string, values?: Record<string, string | number>) => string;
  tCommon: (key: string, values?: Record<string, string | number>) => string;
  tFlow: (key: string) => string;
};

/** Presentation layer — maps i18n keys to serializable CazariLabels patterns. */
export function buildCazariLabels({
  tPages,
  tCommon,
  tFlow,
}: CazariLabelSources): CazariLabels {
  return {
    noContact: tCommon("noContact"),
    noRoom: tPages("noRoomBadge"),
    statusConfirmed: tFlow("confirmata"),
    statusRequest: tFlow("cerere_noua"),
    statusCancelled: tFlow("anulata"),
    details: tCommon("details"),
    refusedHint: tPages("refusedHint"),
    refusedEmpty: tPages("refusedEmpty"),
    refusedEmptyDesc: tPages("refusedEmptyDesc"),
    refusedEmptyFilter: tPages("refusedEmptyFilter"),
    refusedEmptyFilterDesc: tPages("refusedEmptyFilterDesc"),
    historyCancelledSection: tPages("historyCancelledSection", {
      count: "{count}",
    }),
    historyCancelledHint: tPages("historyCancelledHint"),
    historyCancelledBadge: tPages("historyCancelledBadge"),
    historyCancelledAt: tPages("historyCancelledAt", { date: "{date}" }),
    tabOperational: tPages("tabOperational"),
    tabRefused: tPages("tabRefused"),
    refusedBrowseBookings: tPages("refusedBrowseBookings"),
    historyCompletedSection: tPages("historyCompletedSection"),
    historyConfirmedRecentSection: tPages("historyConfirmedRecentSection", {
      count: "{count}",
    }),
    historyConfirmedRecentHint: tPages("historyConfirmedRecentHint"),
    historyConfirmedRecentBadge: tPages("historyConfirmedRecentBadge", {
      date: "{date}",
    }),
    cancelStay: tPages("cancelStay"),
    cancelRequest: tPages("cancelRequest"),
    quickAccept: tPages("quickAccept"),
    quickAcceptSuccess: tPages("quickAcceptSuccess"),
    emitFisa: tPages("emitFisa"),
    completeCheckinForFisa: tPages("completeCheckinForFisa"),
    checkInOnlyOnArrivalDay: tPages("checkInOnlyOnArrivalDay", {
      date: "{date}",
    }),
    guestsShort: tCommon("guestsShort", {
      adults: "{adults}",
      children: "{children}",
    }),
    cancelConfirmedMsg: tPages("cancelConfirmedMsg", {
      ref: "{ref}",
      name: "{name}",
      period: "{period}",
    }),
    cancelRequestMsg: tPages("cancelRequestMsg", {
      ref: "{ref}",
      name: "{name}",
      period: "{period}",
    }),
    emptyConfirmed: {
      title: tPages("emptyConfirmedActive"),
      description: tPages("emptyConfirmedActiveDesc"),
      href: "/admin/calendar",
      label: tPages("openCalendar"),
    },
    emptyConfirmedFilter: {
      title: tPages("emptyConfirmedFilter"),
      description: tPages("emptyConfirmedFilterDesc"),
      href: "/admin/cazari?view=confirmate",
      label: tCommon("reset"),
    },
    emptyRequest: {
      title: tPages("emptyRequestWaiting"),
      description: tPages("emptyRequestWaitingDesc"),
      href: "/admin/calendar",
      label: tPages("openCalendar"),
    },
    emptyRequestFilter: {
      title: tPages("emptyRequestFilter"),
      description: tPages("emptyRequestFilterDesc"),
      href: "/admin/cazari?view=cereri",
      label: tCommon("reset"),
    },
    historyFiltered: tPages("historyFiltered", { count: "{count}" }),
    historyRecent: tPages("historyRecent", { count: "{count}" }),
    historyFilteredHint: tPages("historyFilteredHint"),
    historyRecentHint: tPages("historyRecentHint"),
    tryOtherCriteria: tPages("tryOtherCriteria"),
    historyWillAppear: tPages("historyWillAppear"),
    historyEmptyFilter: tPages("historyEmptyFilter"),
    historyEmpty: tPages("historyEmpty"),
    checkout: tCommon("checkout"),
    openBooking: tCommon("openBooking"),
    acceptAgain: tPages("acceptAgain"),
    acceptAgainHint: tPages("acceptAgainHint"),
    undoCancelConfirm: tPages("undoCancelConfirm"),
    openClientProfile: tPages("openClientProfile"),
    checkIn: tCommon("checkIn"),
    checkInContinue: tPages("checkInContinue"),
    checkInNextRoom: tPages("checkInNextRoom"),
    checkinRoomsProgress: tPages("checkinRoomsProgress", {
      checked: "{checked}",
      total: "{total}",
    }),
    checkinRoomChecked: tPages("checkinRoomChecked"),
    checkinRoomPending: tPages("checkinRoomPending"),
    checkinRoomKeyHanded: tPages("checkinRoomKeyHanded"),
    checkinRoomIdVerified: tPages("checkinRoomIdVerified"),
    checkinRoomIdMissing: tPages("checkinRoomIdMissing"),
    checkinAllRoomsDone: tPages("checkinAllRoomsDone"),
    checkinPartialHint: tPages("checkinPartialHint"),
    edit: tCommon("edit"),
    movePrevDay: tPages("movePrevDay"),
    moveNextDay: tPages("moveNextDay"),
    checkoutNeedsCheckin: tPages("checkoutNeedsCheckin"),
    checkoutAlreadyDone: tPages("checkoutAlreadyDone"),
    checkActionsOnlyConfirmed: tPages("checkActionsOnlyConfirmed"),
    moveOnlyConfirmed: tPages("moveOnlyConfirmed"),
    phoneRequiredForCheckIn: tPages("phoneRequiredForCheckIn"),
    starsShort: tPages("starsShort"),
    groupedToday: tPages("groupedToday", { count: "{count}" }),
    groupedThisWeek: tPages("groupedThisWeek", { count: "{count}" }),
    groupedThisMonth: tPages("groupedThisMonth", { count: "{count}" }),
    groupedUpcoming: tPages("groupedUpcoming", { count: "{count}" }),
    groupedTodayHint: tPages("groupedTodayHint"),
    groupedThisWeekHint: tPages("groupedThisWeekHint"),
    groupedThisMonthHint: tPages("groupedThisMonthHint"),
    groupedUpcomingHint: tPages("groupedUpcomingHint"),
    groupedOutsideWindow: tPages("groupedOutsideWindow", { count: "{count}" }),
    horizonToday: tPages("horizonToday"),
    horizonWeek: tPages("horizonWeek"),
    horizon30d: tPages("horizon30d"),
    horizon60d: tPages("horizon60d"),
    horizon180d: tPages("horizon180d"),
    horizon365d: tPages("horizon365d"),
    loadMore: tPages("loadMore"),
    visibleWindow: tPages("visibleWindow"),
  };
}
