import type { CazariPageLists } from "@/services/cazari-page-data";

export type OperationalStay = CazariPageLists["stays"][number];
export type HistoryStay = CazariPageLists["history"][number];
export type CancelledStay = CazariPageLists["cancelledHistory"][number];
export type StayCardRow = OperationalStay | CancelledStay;

export type CazariLabels = {
  noContact: string;
  noRoom: string;
  statusConfirmed: string;
  statusRequest: string;
  statusCancelled: string;
  details: string;
  refusedHint: string;
  refusedEmpty: string;
  refusedEmptyDesc: string;
  refusedEmptyFilter: string;
  refusedEmptyFilterDesc: string;
  historyCancelledSection: (count: number) => string;
  historyCancelledHint: string;
  historyCancelledBadge: string;
  historyCancelledAt: (date: string) => string;
  tabOperational: string;
  tabRefused: string;
  refusedBrowseBookings: string;
  historyCompletedSection: string;
  historyConfirmedRecentSection: (count: number) => string;
  historyConfirmedRecentHint: string;
  historyConfirmedRecentBadge: (date: string) => string;
  cancelStay: string;
  cancelRequest: string;
  quickAccept: string;
  quickAcceptSuccess: string;
  emitFisa: string;
  completeCheckinForFisa: string;
  checkInOnlyOnArrivalDay: (date: string) => string;
  guestsShort: (adults: number, children: number) => string;
  cancelConfirmedMsg: (ref: string, name: string, period: string) => string;
  cancelRequestMsg: (ref: string, name: string, period: string) => string;
  emptyConfirmed: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  emptyRequest: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  historyFiltered: (count: number) => string;
  historyRecent: (count: number) => string;
  historyFilteredHint: string;
  historyRecentHint: string;
  tryOtherCriteria: string;
  historyWillAppear: string;
  historyEmptyFilter: string;
  historyEmpty: string;
  checkout: string;
  openBooking: string;
  acceptAgain: string;
  acceptAgainHint: string;
  undoCancelConfirm: string;
  openClientProfile: string;
  checkIn: string;
  checkInContinue: string;
  checkInNextRoom: string;
  checkinRoomsProgress: (checked: number, total: number) => string;
  checkinRoomChecked: string;
  checkinRoomPending: string;
  checkinAllRoomsDone: string;
  checkinPartialHint: string;
  edit: string;
  movePrevDay: string;
  moveNextDay: string;
  checkoutNeedsCheckin: string;
  checkoutAlreadyDone: string;
  checkActionsOnlyConfirmed: string;
  moveOnlyConfirmed: string;
  phoneRequiredForCheckIn: string;
  behaviorShort: string;
  loyaltyShort: string;
  starsShort: string;
  groupedToday: (count: number) => string;
  groupedThisWeek: (count: number) => string;
  groupedThisMonth: (count: number) => string;
  groupedUpcoming: (count: number) => string;
  groupedTodayHint: string;
  groupedThisWeekHint: string;
  groupedThisMonthHint: string;
  groupedUpcomingHint: string;
  groupedOutsideWindow: (count: number) => string;
  horizonToday: string;
  horizonWeek: string;
  horizon30d: string;
  horizon60d: string;
  horizon180d: string;
  horizon365d: string;
  loadMore: string;
  visibleWindow: string;
};
