import type { CazariPageLists } from "@/services/cazari-page-data";

export type OperationalStay = CazariPageLists["stays"][number];
export type HistoryStay = CazariPageLists["history"][number];
export type CancelledStay = CazariPageLists["cancelledHistory"][number];
export type StayCardRow = OperationalStay | CancelledStay;

export type CazariLabels = {
  noContact: string;
  noRoom: string;
  statusConfirmed: string;
  statusRequest: string;
  statusCancelled: string;
  details: string;
  refusedHint: string;
  refusedEmpty: string;
  refusedEmptyDesc: string;
  refusedEmptyFilter: string;
  refusedEmptyFilterDesc: string;
  historyCancelledSection: string;
  historyCancelledHint: string;
  historyCancelledBadge: string;
  historyCancelledAt: string;
  tabOperational: string;
  tabRefused: string;
  refusedBrowseBookings: string;
  historyCompletedSection: string;
  historyConfirmedRecentSection: string;
  historyConfirmedRecentHint: string;
  historyConfirmedRecentBadge: string;
  cancelStay: string;
  cancelRequest: string;
  quickAccept: string;
  quickAcceptSuccess: string;
  emitFisa: string;
  completeCheckinForFisa: string;
  checkInOnlyOnArrivalDay: string;
  guestsShort: string;
  cancelConfirmedMsg: string;
  cancelRequestMsg: string;
  emptyConfirmed: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  emptyConfirmedFilter: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  emptyRequest: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  emptyRequestFilter: {
    title: string;
    description: string;
    href: string;
    label: string;
  };
  historyFiltered: string;
  historyRecent: string;
  historyFilteredHint: string;
  historyRecentHint: string;
  tryOtherCriteria: string;
  historyWillAppear: string;
  historyEmptyFilter: string;
  historyEmpty: string;
  checkout: string;
  openBooking: string;
  acceptAgain: string;
  acceptAgainHint: string;
  undoCancelConfirm: string;
  openClientProfile: string;
  checkIn: string;
  checkInContinue: string;
  checkInNextRoom: string;
  checkinRoomsProgress: string;
  checkinRoomChecked: string;
  checkinRoomPending: string;
  checkinRoomKeyHanded: string;
  checkinRoomIdVerified: string;
  checkinRoomIdMissing: string;
  checkinAllRoomsDone: string;
  checkinPartialHint: string;
  edit: string;
  movePrevDay: string;
  moveNextDay: string;
  checkoutNeedsCheckin: string;
  checkoutAlreadyDone: string;
  checkActionsOnlyConfirmed: string;
  moveOnlyConfirmed: string;
  phoneRequiredForCheckIn: string;
  starsShort: string;
  groupedToday: string;
  groupedThisWeek: string;
  groupedThisMonth: string;
  groupedUpcoming: string;
  groupedTodayHint: string;
  groupedThisWeekHint: string;
  groupedThisMonthHint: string;
  groupedUpcomingHint: string;
  groupedOutsideWindow: string;
  horizonToday: string;
  horizonWeek: string;
  horizon30d: string;
  horizon60d: string;
  horizon180d: string;
  horizon365d: string;
  loadMore: string;
  visibleWindow: string;
};
