import type { AdminPaletteDefinition, AdminPaletteTokens } from "./types";

function t(partial: AdminPaletteTokens): AdminPaletteTokens {
  return partial;
}

/** Metadata + preview tokens — stilul real e în src/styles/themes/*.css */
export const CATALOG_PALETTES: AdminPaletteDefinition[] = [
  {
    id: "default",
    name: "Default",
    description: "Alb simplu — curat, fără efecte decorative",
    group: "catalog",
    day: t({
      pageBg: "#ffffff",
      panelBg: "#ffffff",
      panelBorder: "#e4e4e7",
      text: "#18181b",
      textMuted: "#71717a",
      accent: "#3f3f46",
      accentMuted: "#f4f4f5",
      ganttZoneCheckout: "#fafafa",
      ganttZoneClean: "#ffffff",
      ganttZoneCheckin: "#f4f4f5",
      ganttLineCheckout: "#a1a1aa",
      ganttLineCheckin: "#d4d4d8",
      hudGradient: "#ffffff",
      hudText: "#18181b",
      hudEyebrow: "#71717a",
    }),
    night: t({
      pageBg: "#09090b",
      panelBg: "#18181b",
      panelBorder: "#27272a",
      text: "#fafafa",
      textMuted: "#a1a1aa",
      accent: "#e4e4e7",
      accentMuted: "#27272a",
      ganttZoneCheckout: "#1c1917",
      ganttZoneClean: "#18181b",
      ganttZoneCheckin: "#27272a",
      ganttLineCheckout: "#71717a",
      ganttLineCheckin: "#52525b",
      hudGradient: "#18181b",
      hudText: "#fafafa",
      hudEyebrow: "#a1a1aa",
    }),
  },
  {
    id: "win95",
    name: "Windows 95",
    description: "Desktop teal, taskbar gri, ferestre 3D",
    group: "catalog",
    day: t({
      pageBg: "#008080",
      panelBg: "#c0c0c0",
      panelBorder: "#808080",
      text: "#000000",
      textMuted: "#404040",
      accent: "#000080",
      accentMuted: "#dfdfdf",
      ganttZoneCheckout: "#ffffcc",
      ganttZoneClean: "#ffffff",
      ganttZoneCheckin: "#c0c0c0",
      ganttLineCheckout: "#000080",
      ganttLineCheckin: "#808080",
      hudGradient: "linear-gradient(180deg, #c0c0c0, #dfdfdf)",
      hudText: "#000000",
      hudEyebrow: "#000080",
    }),
    night: t({
      pageBg: "#004040",
      panelBg: "#c0c0c0",
      panelBorder: "#808080",
      text: "#000000",
      textMuted: "#404040",
      accent: "#000080",
      accentMuted: "#808080",
      ganttZoneCheckout: "#ffffcc",
      ganttZoneClean: "#c0c0c0",
      ganttZoneCheckin: "#808080",
      ganttLineCheckout: "#000080",
      ganttLineCheckin: "#404040",
      hudGradient: "linear-gradient(180deg, #808080, #a0a0a0)",
      hudText: "#ffffff",
      hudEyebrow: "#c0c0c0",
    }),
  },
  {
    id: "winxp",
    name: "Windows XP Classic",
    description: "Bliss XP + ferestre Luna",
    group: "catalog",
    day: t({
      pageBg: "#5a9fd4",
      panelBg: "#ffffff",
      panelBorder: "#0054e3",
      text: "#003399",
      textMuted: "#3366cc",
      accent: "#0054e3",
      accentMuted: "#ece9d8",
      ganttZoneCheckout: "#fffacd",
      ganttZoneClean: "#ffffff",
      ganttZoneCheckin: "#d3e5ff",
      ganttLineCheckout: "#ff8c00",
      ganttLineCheckin: "#0054e3",
      hudGradient: "linear-gradient(180deg, #0997ff, #3c92f8)",
      hudText: "#ffffff",
      hudEyebrow: "#c8e7ff",
    }),
    night: t({
      pageBg: "#1a3a5c",
      panelBg: "#f0f4fc",
      panelBorder: "#0997ff",
      text: "#003399",
      textMuted: "#5a7ab8",
      accent: "#3c92f8",
      accentMuted: "#d8e8ff",
      ganttZoneCheckout: "#3d3200",
      ganttZoneClean: "#e8eef8",
      ganttZoneCheckin: "#b8d4f0",
      ganttLineCheckout: "#c97800",
      ganttLineCheckin: "#3c92f8",
      hudGradient: "linear-gradient(180deg, #0a246a, #3c92f8)",
      hudText: "#ffffff",
      hudEyebrow: "#93c5fd",
    }),
  },
];
